apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: giriappofapps
  namespace: argocd
spec:
  destination:
    namespace: argocd
    name: in-cluster
  project: default
  source:
    path: appofapps
    repoURL: https://github.com/girichinna27/wisetech-argocd-apps.git
    targetRevision: master
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
